# Generated by Django 3.2.18 on 2023-06-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230616_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ManyToManyField(related_name='project_department', to='base.Department'),
        ),
    ]
