# Generated by Django 3.2.18 on 2023-06-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_shot_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='task_shot', to='base.shot'),
            preserve_default=False,
        ),
    ]
