# Generated by Django 3.2.18 on 2023-06-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_task_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='task_department', to='base.department'),
            preserve_default=False,
        ),
    ]
