# Generated by Django 3.2.18 on 2023-06-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
    ]
