# Generated by Django 3.2.18 on 2023-06-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_task_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermissions',
            options={'default_permissions': [], 'permissions': (('add_announcement', 'add_announcement'), ('employee_manager', 'employee_manager'), ('employee_manager_manager', 'employee_manager_manager'), ('employee_manager_admin', 'employee_manager_admin'), ('attendance', 'attendance'), ('attendance_readonly', 'attendance_readonly'), ('attendance_admin', 'attendance_admin'), ('attendance_prod_view', 'attendance_prod_view'), ('leave_manager', 'leave_manager'), ('leave_manager_lead', 'leave_manager_lead'), ('leave_manager_manager', 'leave_manager_manager'), ('leave_manager_admin', 'leave_manager_admin'), ('team_manager', 'team_manager'), ('team_manager_admin', 'team_manager_admin'), ('team_manager_manager', 'team_manager_manager'), ('clients_list', 'clients_list'), ('vendors_list', 'vendors_list'), ('projects_list', 'projects_list'), ('projects_list_add_project', 'projects_list_add_project'), ('projects_overview', 'projects_overview'), ('projects_permission', 'projects_permission'), ('projects', 'projects'), ('task_overview', 'task_overview'), ('task_overview_add_subtask', 'task_overview_add_subtask'), ('resource_planner', 'resource_planner'), ('resource_planner_update', 'resource_planner_update'), ('ingest_system', 'ingest_system'), ('bidding_system', 'bidding_system'), ('bidding_system_bid_rate', 'bidding_system_bid_rate'), ('site_sync', 'site_sync'), ('tasks_list', 'tasks_list'), ('shots_list', 'shots_list'), ('artist_utilization', 'artist_utilization'), ('workstations', 'workstations'), ('file_transfer', 'file_transfer'), ('project_archival', 'project_archival'), ('transportation_page', 'transportation_page'), ('vehicle_directory', 'vehicle_directory'), ('gmail_group', 'gmail_group'), ('create_gmail_group', 'create_gmail_group'), ('tickets', 'tickets'), ('tickets_maintainer', 'tickets_maintainer'), ('tickets_admin', 'tickets_admin'))},
        ),
        migrations.AddField(
            model_name='shot',
            name='annotation',
            field=models.TextField(default='/static/img/default_poster.png'),
        ),
        migrations.AddField(
            model_name='shot',
            name='bids',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='client_feedback',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='client_remarks',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='execution_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='fps',
            field=models.FloatField(default=24),
        ),
        migrations.AddField(
            model_name='shot',
            name='internal_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_position', to='base.userprofile', to_field='full_name'),
        ),
        migrations.AddField(
            model_name='shot',
            name='internal_supervisor_remarks',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='show_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='thumbnail',
            field=models.TextField(default='/static/img/default_poster.png'),
        ),
        migrations.AddField(
            model_name='shot',
            name='vault_url',
            field=models.URLField(null=True),
        ),
    ]
