# Generated by Django 3.2.18 on 2023-06-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230622_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complexity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_complexity', to='base.taskcomplexity'),
        ),
    ]
